dependencies:
  - conda-forge::numpy=1.19.2
  - conda-forge::pip=21.0.1
  - conda-forge::python=3.9.18
  - pip:
      - matplotlib==3.4.3
      - arviz==0.12.1
      - git+https://git.ligo.org/amanda.farah/mock-PE.git@main
      - jax==0.4.18
      - jaxlib==0.4.18
      - numpyro==0.10.0  
      - tinygp==0.2.3
      - scipy==1.8.1
      - netcdf4==1.6.0
